name: growthbook_sdk_flutter
description: An open-source feature flagging and experimentation platform that makes it simple to alter features and execute A/B testing.
version: 3.0.0+0
repository: https://github.com/alippo-com/GrowthBook-SDK-Flutter

environment:
  sdk: ">=2.17.2 <4.0.0"

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  analyzer: ^4.6.0
  json_serializable: ^6.2.0
